In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.0'

In [3]:
list1 = [2, 3, 4, 6]

In [4]:
arr1 = np.array(list1)

In [5]:
arr1

array([2, 3, 4, 6])

In [6]:
arr1.shape

(4,)

In [7]:
arr1.size

4

In [8]:
def reverse_array(array):
    i = 0
    j = len(array) - 1
    while i < j:
        t = array[i]
        array[i] = array[j]
        array[j] = t
        i += 1
        j -= 1
    return array

In [9]:
print(reverse_array(arr1))

[6 4 3 2]


In [10]:
list1 = [2, 3, 4, 6]
list2 = [8, 10, 12, 14]

In [11]:
arr2 = np.array([list1, list2])

In [12]:
arr2

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14]])

In [13]:
arr2.shape

(2, 4)

In [14]:
arr2.size

8

In [15]:
list1 = [2, 3, 4, 6]
list2 = [8, 10, 12, 14]
list3 = [16, 18, 20, 22.1]

In [16]:
arr3 = np.array([list1, list2, list3], dtype=int)

In [17]:
arr3

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])