In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=10)

In [5]:
r1 = rng.integers(10, 20, size=(2, 3))
r2 = rng.integers(10, 20, size=(1, 3))
print(r1)
print(r2)

[[15 19 12]
 [18 10 13]]
[[17 15 19]]


In [6]:
r1 + r2

array([[32, 34, 31],
       [35, 25, 32]])

In [7]:
np.dot(r1, r2.T)

array([[768],
       [703]])