In [1]:
import numpy as np

In [4]:
list_numbers = [[12, 23, -45], [18, -77, -44]]
arr = np.array(list_numbers)
arr

array([[ 12,  23, -45],
       [ 18, -77, -44]])

In [6]:
[int(i) for r in arr for i in r if i < 0]

[-45, -77, -44]

In [8]:
arr2 = arr  * 2
arr2

array([[  24,   46,  -90],
       [  36, -154,  -88]])

In [9]:
np.sum(arr2, axis=1)

array([ -20, -206])

In [10]:
np.sum(arr2, axis=0)

array([  60, -108, -178])

In [12]:
arr3 = np.arange(100).reshape((2, 5, 10))
arr3

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [14]:
arr3[1, 0, :]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [15]:
np.greater(arr[0], arr[1])

array([False,  True, False])