In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(123)

In [3]:
arr = rng.integers(20, size=(10,))

In [4]:
arr

array([ 0, 13, 11,  1, 18,  4,  5,  3,  6,  3])

In [5]:
arr2 = np.array([arr[2], arr[4], arr[7]])

In [6]:
arr2

array([11, 18,  3])

In [9]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
arr3 = np.array(my_list)

In [10]:
arr3[:, 2]

array([ 3,  8, 13])